### ISSUE TITLE
Need help identifying a MCU from 1988 toyota cressida digital dash

### ISSUE THREAD

**Issue by putraadr** [sparkiedk/Toyota-PCM-hacking#5]
Hello Sparkiedk!, I'm currently tinkering with my spare vfd digital dash for my 1988 cressida. I'm sorry if i go out of topic :)
I want to take control the RPM, fuel and temp display to use Arduino as the main processor... this cluster is using unknown 40-pin chip.

i looked everywhere for datasheet but no luck.. the chip marking says "F145-7958 Intel'80"  
Here's a picture of the chip : [CPU.jpeg](http://putranetwork.coffeecup.com/se/cressida/CPU.jpeg)
Here's a collection of my cluster board pictures : [digital dash pictures](http://putranetwork.coffeecup.com/se/cressida)
do you have any idea what is this chip? thanks in advance :)

**Comment by sparkiedk** [comment]
I found your stackexchange post, and those people are saying the same thing I was thinking: "copyright intel '80" immediately screams 8051 to me:
https://en.wikipedia.org/wiki/Intel_8051
_"The Intel MCS-51 (commonly termed 8051) is a single chip microcontroller (MCU) series developed by Intel in 1980 for use in embedded systems."_

What I would do first is check to see if pin 40 is on your VCC bus, pin 20 is on your VSS bus and a crystal is attached between pins 18 and 19, if that's the case then I would move forward with the assumption that this chip is an 8051. If they didn't get too sassy back in 88 then it would be possible to desolder the chip from the board, drop it into an eprom reader with a special adapter and dump the rom contents of the chip.
Do keep in mind you must put substantive reverse engineering into figuring out how the board works around the microcontroller, and really if you intend to outright replace it then you might not benefit much from the code at all - RPM will equal 60*(igniter pulses per second)/3. speed is probably marked on the gauge cluster somewhere (as I recall my supra is 637 rotations per kilometer, which spins a magnet that toggles a reed relay 4 times per rotation). fuel and temp will be analog values (temp is usually a 10k NTC and it's standard across all toyotas, the 1UZ sensor drives my 82 analog dash perfectly)

some other notes I got:
c494c is a UPC494 switch mode power supply driver (they still make these, they kinda suck but they get the job done)
tc4013 is a D flip flop
tc4066 is a quad bilateral switch (cool part!)
tc4081 is a quad AND gate
tc4093 is a quad NAND gate
tc40103 is a down counter

hopefully you find what let the smoke out too, perhaps removing that part will allow much of the rest of the board to function and yield its secrets through active probing rather than passive analysis.

**Comment by sparkiedk** [comment]
Hey I just found this, which contains the string "8637" and suggests it could be an intel 8035
https://www.cpu-galaxy.at/cpu/Ram%20Rom%20Eprom/Microcontroller/Intel%208035%20section.htm

have you made any progress chasing down the power and oscillator connections?
